### ISSUE TITLE
How do i detect Control key sequences?

### ISSUE THREAD

**Issue by Vaxeral** [jquast/blessed#222] opened 2021-10-10 23:37 UTC
Im trying to detect ctrl+c or other variants in my vscode terminal.  Ctrl sequences seem to not appear when using inkey.

**Comment by avylove** [comment] 2021-10-11 11:49
Are you using using [cbreak](https://blessed.readthedocs.io/en/latest/api/terminal.html#blessed.terminal.Terminal.cbreak) or [raw](https://blessed.readthedocs.io/en/latest/api/terminal.html#blessed.terminal.Terminal.raw) mode? You'll need raw mode in order to capture some control sequences.

**Comment by Vaxeral** [comment] 2021-10-12 07:25
im in raw mode.  I saw your other issues and i found that i could use the sequence \x01 for control c for example.

**Comment by Minabsapi** [comment] 2022-10-16 21:36
Same thing for me. Variant of the "rich event loop" snippet for reference:

```python
#!/bin/python3

from blessed import Terminal

term = Terminal()

print(f"{term.home}{term.black_on_skyblue}{term.clear}")
print("press 'q' to quit.")
with term.raw():
    val = ''
    while val.lower() != 'q':
        val = term.inkey(timeout=3)
        if not val:
           print("It sure is quiet in here ...")
        elif val.is_sequence:
           print("got sequence: {0}.".format((str(val), val.name, val.code)))
        elif val:
           print(f"got {val}. ({val.code})")
    print(f'bye!{term.normal}')
```

When launching it from Bash, almost all `Keystroke` object on Ctrl modifier sequences have a code `None`. Some exceptions:
- Ctrl + I: '\t'
- Ctrl + J: '\n'
- Ctrl + H: '\x08'
- Ctrl + M: '\n'

**Comment by avylove** [comment] 2022-10-17 03:01
What's an example of a key you're seeing in keymatrix that you aren't seeing in the above code?

**Comment by jquast** [comment] 2022-10-17 13:50
Hello @Minabsapi,

Try changing,
```
           print(f"got {val}. ({val.code})")
```

to,
```
           print(f"got {val!r}. ({val.code})")
```

that is, display repr(val) rather than str(val) -- as the `val` in this case is the raw control character. When written to stdout, most terminals do not display anything

**Comment by jquast** [comment] 2024-06-26 21:32
Closing as duplicate of #58

**Closed by jquast** 2024-06-26 21:32 UTC
