### ISSUE TITLE
Add a way to know if the mouse clicks on some text.

### ISSUE THREAD

**Issue by MonAaraj** [jquast/blessed#174] opened 2020-06-14 21:12 UTC
Hi, I have been looking at the docs and reviewing the examples of this library and I found it amazing, but it has a downside, the inability to kind of make somethings like "widgets" with its simplicity, e.g. TUI buttons are an inconvenience to implement with the current set up, and trying to implement more widgets could potentially end up harder, any way to make it at the least easier for people to create their own widgets, at most have some barebones widgets implementation? Maybe, it could have to do with comparing the (x, y) of the cursor's click event and the area that the text spans?

**Comment by jquast** [comment] 2020-06-15 14:55
duplicate of #7, code already exists, just needs to be added with tests and a PR.

As for a TUI, I'm open to *very primitive* user interface additions (#167, #134), perhaps a basic readline implementation, but I don't wish to add anything beyond a few dozen lines of code for each widget, and they must come with tests and documentation.

blessed is to SDL as Urwid and others are to Qt. Blessed just wishes to provide the basic, portable primitives for building terminal apps and libraries without any opinion on appearance or interface.

"Widgets" are very stylistic and opinionated, folks would want the appearance to be very customizable, and with, or without, asyncio support, to support asynchronous code, or by callbacks, etc. It would quickly enlarge the library size and still yet, many folks might be unsatisfied with the API.

I've done a lot of work in building a TUI above blessed in an old project of mine (x84), and yet downstream developers/users would go on to customize and write their own TUI's anyway, for style reasons, a majority of the code I wrote was to support customization, "themes" and so on, but the documentation wasn't there, it was all too overwhelming, it's a very difficult problem.

For great input, try https://github.com/prompt-toolkit/python-prompt-toolkit/
for great TUI, try https://github.com/urwid/urwid 
Or https://github.com/CITGuru/PyInquirer

blessed can interoperate with any other curses library, so it's no problem to mix and match them together. best wishes and thanks for your thoughts

**Closed by jquast** 2020-06-15 14:55 UTC
